spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lgdtest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
    username: root
    password: 1328910
    driver-class-name: com.mysql.cj.jdbc.Driver
