#server.port= ${random.int[1024,9999]}
server:
  port: 8080
com:
  lgd : hello,lgd!
logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} -%msg%n'
    file: '%d{yyyy-MM-dd} === [%thread] == %-5level == %logger{50} == %msg%n'
  file:
    path: output/logs
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lgdtest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
    username: root
    password: 1328910
    driver-class-name: com.mysql.cj.jdbc.Driver
